### ISSUE TITLE
error when use _flow_warp_grad

### ISSUE THREAD

**Issue by jgj1986** [sampepose/flownet2-tf#1]
Please review code about `_flow_warp_grad()` in `src/flow_warp.py `:
whether this function should be calling `_flow_warp_ops.flow_warp_grad()`,  but not `_correlation_ops.correlation_grad()` ？

**Comment by MarcyLee** [comment]
same problem encountered.

**Comment by sampepose** [comment]
This should be fixed now with 43a138b. Thank you!
