### ISSUE TITLE
Intermedia npy file

### ISSUE THREAD

**Issue by Yuliang-Zou** [sampepose/flownet2-tf#11]
Hi, thanks for sharing this code. Can you also share the intermedia npy file of the model weights? Since installing Caffe on my cluster is a bit tricky, I wanna have the npy to feed my TensorFlow model.

Thank you!

**Comment by sampepose** [comment]
Hi!

The weights are saved as TF checkpoints. You can load them as such using a Saver.

If you still need the npy weights, I may be able to get them later this week.

SP

**Comment by Yuliang-Zou** [comment]
Problem solved. Thank you!
