### ISSUE TITLE
Not able to run on CPU

### ISSUE THREAD

**Issue by NitinJSanket** [sampepose/flownet2-tf#2]
Hi,
Thanks for your awesome code. It runs extremely well on the GPU but I was wondering if it can be run on CPU?

Thanks,
Nitin

**Comment by sampepose** [comment]
Hi Nitin,

Right now the custom TF operations are written for GPU-use only, so this cannot be used on a CPU only. I'd welcome any PR to make them available on the CPU. I'm sorry, but I don't have time at the moment to write that code.

Best,
Sam
