### ISSUE TITLE
Code license

### ISSUE THREAD

**Issue by nikolausmayer** [sampepose/flownet2-tf#3]
Hi Sam,

great job on the TF implementation! We would like to make use of (some of) your code and the ported models, but there is currently no license on this repository. If you are ok with us using it, could I ask you to add a license or give us permission to do so? :)

Thanks,
 Nikolaus

**Comment by sampepose** [comment]
Hi Nikolaus,

Thank you! I just added an MIT license. You're welcome to use any of the code. If you use a substantial amount of code, I'd really appreciate a shoutout in an acknowledgment section :)

Best,
Sam

**Comment by nikolausmayer** [comment]
That's perfect, thank you. A proper acknowledgement is a given, of course!
