### ISSUE TITLE
Is there a good method or labeling tool to create ground truth data to fine tune flownet2 on new video datasets?

### ISSUE THREAD

**Issue by Santana18** [sampepose/flownet2-tf#33]
Would be happy about some hint, if a good process exists.

**Comment by sampepose** [comment]
It's pretty simple for synthetic datasets (like Sintel). You can use blender or unity to create your scene, then use built-in tools in the renderer to output optical flow.

It's a lot trickier for real videos. You could try running them through flownet2 as a prior and then manually clean them up with an annotation tool like Mechanical Turk. This is a good paper explaining how ground-truth OF dataset can be generated if you're recording yourself (http://vision.middlebury.edu/flow/floweval-ijcv2011.pdf).
