### ISSUE TITLE
Input preprocessing to use pretrained weights

### ISSUE THREAD

**Issue by CarolusM** [sampepose/flownet2-tf#35]
I have FlowNetS running with its pretrained weights but I was wondering wheter I should normalize the input images in the range (0,1) or in the range (-1,1). As far as I know, I need to normalize the input images in the same range that it was done while training the weights provided.

Any help would be highly appreciated. Thanks in advance!

**Comment by sampepose** [comment]
Your input images should be RGB in the range (0.0, 1.0).

You can see here that it will automatically rescale from (0, 255) to (0.0, 1.0) if needed when doing a test run: https://github.com/sampepose/flownet2-tf/blob/master/src/net.py#L45-L53
