### ISSUE TITLE
Unable to do make with Tensorflow1.2.1, Python 2.7, Cuda 8.0, CuDNN 6.0

### ISSUE THREAD

**Issue by cahuja1992** [sampepose/flownet2-tf#48]
nvcc -g -std=c++11 -I`python -c "import tensorflow; print(tensorflow.sysconfig.get_include())"` -I"/usr/local/cuda-8.0/.." -DGOOGLE_CUDA=1 -D_MWAITXINTRIN_H_INCLUDED -D_FORCE_INLINES -D__STRICT_ANSI__ -D_GLIBCXX_USE_CXX11_ABI=0 -c src/ops/preprocessing/kernels/data_augmentation.cu.cc -x cu -Xcompiler -fPIC  -o src/ops/build/data_augmentation.o
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
In file included from /home/chirag/.local/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/platform/stream_executor.h:26:0,
                 from /home/chirag/.local/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/util/cuda_kernel_helper.h:27,
                 from src/ops/preprocessing/kernels/data_augmentation.cu.cc:7:
/home/chirag/.local/lib/python2.7/site-packages/tensorflow/include/tensorflow/stream_executor/dso_loader.h:32:30: fatal error: cuda/cuda_config.h: No such file or directory
compilation terminated.

**Comment by LiuzhuForFun** [comment]
@cahuja1992 ,Hi,How did you solve it?
