### ISSUE TITLE
show the Image after processed by preprocessing.so

### ISSUE THREAD

**Issue by xue1liu2** [sampepose/flownet2-tf#5]
I want to see the image after it processed by preprocessing.so ,So I just got the preprocessing.so and compiled.

  I read the image by cv2,and send it to the imageprocess function,but it doesn't work.
 It successfully invokes the library file(preprocessing.so), When I want to get it by sess.run[image_as,image_bs,flows], It stopped. and gave the Error message.

Error message:
   process finished with code 139 (interrupted by signal 11: SIGSEVG)

Have you ever had this problem?

**Comment by xue1liu2** [comment]
DiD you compile on your Linux System14.04, on system 14.04 the preprocessing.so works well.
But  when I compile it on 16.04, the preprocessing.so doen't work? Do you know why?

**Comment by sampepose** [comment]
I compiled on Ubuntu 14.04. I'm not sure why it wouldn't work on 16.04, but I don't have access to that OS right now.
