### ISSUE TITLE
About the correlation layer

### ISSUE THREAD

**Issue by JoeFang123** [sampepose/flownet2-tf#60]
I want to train the network by myself, I wonder whether I have to compile the files in _ops_ or not? I found that the document called _build_ in _ops_ is empty and there no compiled files. I will appreciate it, if you can offer any kind of help.

**Comment by Iamanorange** [comment]
You need to compile the ops.

The directory `flownet2-tf/src/ops/build` is empty because it contains binary files which is not suitable to be tracked by Git.
