### ISSUE TITLE
undefined symbol: __cudaPushCallConfiguration

### ISSUE THREAD

**Issue by mengyaaa** [sampepose/flownet2-tf#67]
python main.py
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    import models, losses, datasets
  File "/root/flownet2-pytorch-master/models.py", line 8, in <module>
    from networks.resample2d_package.resample2d import Resample2d
  File "/root/flownet2-pytorch-master/networks/resample2d_package/resample2d.py", line 3, in <module>
    import resample2d_cuda
ImportError: /root/.local/lib/python3.6/site-packages/resample2d_cuda-0.0.0-py3.6-linux-x86_64.egg/resample2d_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPushCallConfiguration

**Comment by Iamanorange** [comment]
What's your environment and what did you do before `python main.py`?

**Comment by mengyaaa** [comment]
> What's your environment and what did you do before `python main.py`?

emm...Thank you much for your attention.  
my enviroment ubuntu 16.04  python 3.6.7  cuda10.0  pytorch 0.4.1.post2  numpy 1.15.4 scipy 1.1.0
I ran install.sh before python main.py...there was some WARNINGs.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (/root/anaconda3/envs/tensorflow/bin/x86_64-conda_cos6-linux-gnu-c++) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
then I apt-get install gcc...this is my first time question on GitHub.Thank you for your reply.

**Comment by Iamanorange** [comment]
What `install.sh`? Where did you get it?
Did you compile the custom OPs before `python main.py`?
Seems you are using g++ 4.x in Anaconda. You can try to use system g++ (should be 5.5) instead.

**Comment by mengyaaa** [comment]
> What `install.sh`? Where did you get it?
> Did you compile the custom OPs before `python main.py`?
> Seems you are using g++ 4.x in Anaconda. You can try to use system g++ (should be 5.5) instead.

emm...I am so sorry for my carelessness.I ran two programs at the same time and install.sh come from flownet2-pytorch..thank for your advice..
